### ISSUE TITLE
Segfault on Debian 8 under VirtualBox

### ISSUE THREAD

**Issue by ghost** [magcius/drmdemo#1]
I suspect KMS isn't actually working, but here's the debug output anyway:

```
Starting program: /home/voltagex/src/drmdemo/drmdemo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000004013d3 in device_find_crtc (device=0x7fffffffea80) at device.c:41
41    for (i = 0; i < resources->count_connectors; i++)


#0  0x00000000004013d3 in device_find_crtc (device=0x7fffffffea80)
    at device.c:41
        ret = 0
        resources = 0x0
        connector = 0x7ffff665d670 <main_arena+80>
        encoder = 0x40130d <device_open+39>
        crtc = 0x25
        i = 0
#1  0x000000000040209d in main (argc=1, argv=0x7fffffffeb98) at drmdemo.c:209
        device = {fd = 4, resources = 0x0, connector = 0x0, crtc = 0x0}
        appdata = {device = 0x7fffffffea80, appbuf = {{buffer = {device = 0x0, 
                pixels = 0x0, size = 0, id = 0, handle = 0, width = 0, 
                height = 0, stride = 0}, surface = 0x0, cr = 0x0}, {buffer = {
                device = 0x0, pixels = 0x0, size = 0, id = 0, handle = 0, 
                width = 0, height = 0, stride = 0}, surface = 0x0, cr = 0x0}, {
              buffer = {device = 0x0, pixels = 0x0, size = 0, id = 0, 
                handle = 0, width = 0, height = 0, stride = 0}, surface = 0x0, 
              cr = 0x0}, {buffer = {device = 0x0, pixels = 0x0, size = 0, 
                id = 0, handle = 0, width = 0, height = 0, stride = 0}, 
              surface = 0x0, cr = 0x0}, {buffer = {device = 0x0, pixels = 0x0, 
                size = 0, id = 0, handle = 0, width = 0, height = 0, 
                stride = 0}, surface = 0x0, cr = 0x0}, {buffer = {
                device = 0x0, pixels = 0x0, size = 0, id = 0, handle = 0, 
                width = 0, height = 0, stride = 0}, surface = 0x0, cr = 0x0}, {
              buffer = {device = 0x0, pixels = 0x0, size = 0, id = 0, 
                handle = 0, width = 0, height = 0, stride = 0}, surface = 0x0, 
              cr = 0x0}, {buffer = {device = 0x0, pixels = 0x0, size = 0, 
                id = 0, handle = 0, width = 0, height = 0, stride = 0}, 
              surface = 0x0, cr = 0x0}, {buffer = {device = 0x0, pixels = 0x0, 
                size = 0, id = 0, handle = 0, width = 0, height = 0, 
                stride = 0}, surface = 0x0, cr = 0x0}, {buffer = {
                device = 0x0, pixels = 0x0, size = 0, id = 0, handle = 0, 
                width = 0, height = 0, stride = 0}, surface = 0x0, cr = 0x0}}, 
          curbuf = 0, cursor = {{buffer = {device = 0x0, pixels = 0x0, 
                size = 0, id = 0, handle = 0, width = 0, height = 0, 
                stride = 0}, surface = 0x0, cr = 0x0}, {buffer = {
                device = 0x0, pixels = 0x0, size = 0, id = 0, handle = 0, 
                width = 0, height = 0, stride = 0}, surface = 0x0, cr = 0x0}}, 
          cursor_x = 0, cursor_y = 0, cursor_buf = 0, cursor_dir_x = 0, 
          cursor_dir_y = 0, time = 0, x = 0, dir = 0, craig = 0x0, tiger = 0x0}
        mainloop = 0x610f50
        ret = 1
```

**Comment by ghost** [comment]
Newbie mistake, this requires X11, right?

**Comment by magcius** [comment]
No, it doesn't require X11. I haven't tried VirtualBox though -- do you have guest additions installed, and does `/dev/dri/card0` exist?

**Comment by ghost** [comment]
Got it working on a physical machine running similar software, I will continue troubleshooting.

Meanwhile, it seems to take the X server down when it exits (I was on VT2, X is no longer on VT7 when I manage to exit).

Should I open another issue? There doesn't seem to be an easy way of exiting, either.

**Comment by magcius** [comment]
That's strange -- I've never seen that happen -- the X server seems to survive on my machine here. Intel graphics ThinkPad running Fedora 22.

Right now, we don't actually turn off the underlying TTY from the VT, so the "easy way to exit" is ^C -- you're still typing in the underlying TTY. Adding proper TTY handling is a bit more complicated, but I wouldn't be opposed to adding it.

**Comment by ghost** [comment]
Intel Graphics Thinkpad running Debian 8 here - ctrl-C sometimes works and
then I'm left with a blank screen - ctrl-alt-F whatever will sometimes
work. I'm not entirely sure what's going on there.

**Comment by ghost** [comment]
Back to the issue at hand - this isn't Debian specific. I just reproduced it on an Arch VM where /dev/dri/card0 definitely exists. Similar segfault, strace shows the crash happening:

```
open("/dev/dri/card0", O_RDWR)          = 4
ioctl(4, DRM_IOCTL_MODE_GETRESOURCES, 0x7ffda756f620) = -1 EINVAL (Invalid argument)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20} ---
+++ killed by SIGSEGV (core dumped) +++
```

**Comment by magcius** [comment]
Hm, so somehow `drmModeGetResources` returns `EINVAL`. That doesn't make much sense to me -- I wonder if it's a thing about VirtualBox's DRM driver.

**Comment by magcius** [comment]
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/gpu/drm/drm_crtc.c#n1696 suggests that whatever's in `/dev/dri/card0` is not a modeset device. Perhaps it's VGEM -- are there any other entries in `/dev/dri/`? Do you have the VirtualBox Guest Additions loaded?

**Comment by ghost** [comment]
VirtualBox Guest Additions are enabled, no other devices in `/dev/dri/`

**Comment by magcius** [comment]
I just added a patch to print the driver name -- completely untested (not in a place to compile C code right now), so it might be broken, but try that and tell me what it prints.

**Comment by ghost** [comment]
`Driver name: vboxvideo`

I appreciate all the help - it's definitely not as easy as just opening the framebuffer device.

**Comment by magcius** [comment]
Hm, that is strange -- according to https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Additions/linux/drm/vbox_drv.c it definitely registers as a `DRIVER_MODESET` device, so I wonder why we're hitting that EINVAL path.

I know that Oracle isn't necessarily that great at keeping their builds up to date, so maybe the version of VirtualBox you're using just has really old guest additions? But I don't know why Xorg is working in that case.

**Comment by magcius** [comment]
Indeed, the legacy framebuffer interface tends to be very nice for quick and dirty stuff, but DRM/KMS shouldn't necessarily be any more complicated. I just know VirtualBox has lots of issues with Linux guests, and they've only gotten worse under Sun/Oracle. I've tried to steer people away from them whenever possible.

Other virtualizers like VMWare and qemu/kvm tend to work just fine.

**Comment by ghost** [comment]
I'm running a test build - 5.0.5. QEmu isn't a lot of fun on Windows but I will try that

**Comment by ghost** [comment]
Now that is odd, https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Additions/linux/drm/vbox_drv.c looks like it should have a `modeset` parameter, but neither vboxguest nor vboxvideo have that parameter on my system, at least as far as `modinfo -p` shows.

**Comment by magcius** [comment]
I'm not a VirtualBox expert, but I believe that the OSE and PUEL versions are different, and I forget which is the better one.

**Comment by ghost** [comment]
Not working on this at the moment. If I get back to it I'll re-open, just clearing up my to-do list.
